layout: stacked
style: dark

repository: juletx/juletx.github.io

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: stars
  # sort_by options:
  #   - pushed
  #   - stars
  # limit: 9
  exclude:
    archived: true
    forks: true
    projects:
    # - repo-name

social_media:
  website: https://julenetxaniz.eus
  linkedin: juletxara
  twitter: juletxara
  instagram: juletxara
  facebook: juletxara
  stackoverflow: 12519473
  hackerrank: juletxara
  # behance: your_username
  # dribbble: your_username
  # keybase: your_username
  # mastodon: your_username
  # medium: your_username
  # telegram: your_username
  # unsplash: your_username
  # vk: your_username
  # youtube: your_username

topics:
  - category: Programming Languages
    items:
      - name: Python
        web_url: https://github.com/topics/python
        image_url: https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/python/python-original.svg
      - name: R
        web_url: https://github.com/topics/r
        image_url: https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/r/r-original.svg
      - name: Java
        web_url: https://github.com/topics/java
        image_url: https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/java/java-original-wordmark.svg
      - name: JavaScript
        web_url: https://github.com/topics/javascript
        image_url: https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/javascript/javascript-original.svg
      - name: PHP
        web_url: https://github.com/topics/php
        image_url: https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/php/php-original.svg
      - name: C
        web_url: https://github.com/topics/c
        image_url: https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/c/c-original.svg

  - category: Web Development
    items:
      - name: Bootstrap
        web_url: https://github.com/topics/bootstrap
        image_url: https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/bootstrap/bootstrap-plain.svg
      - name: Tailwind CSS
        web_url: https://github.com/topics/tailwindcss
        image_url: https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/tailwindcss/tailwindcss-original.svg
      - name: Hugo
        web_url: https://github.com/topics/hugo
        image_url: https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/hugo/hugo-original.svg
      - name: Alpine.js
        web_url: https://github.com/topics/alpinejs
        image_url: https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/alpinejs/alpinejs-original.svg
      - name: jQuery
        web_url: https://github.com/topics/jquery
        image_url: https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/jquery/jquery-original.svg
      - name: Netlify
        web_url: https://github.com/topics/netlify
        image_url: https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/netlify/netlify-original.svg

  - category: Machine Learning
    items:
      - name: Scikit-Learn
        web_url: https://github.com/topics/scikit-learn
        image_url: https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/scikitlearn/scikitlearn-original.svg
      - name: TensorFlow
        web_url: https://github.com/topics/tensorflow
        image_url: https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/tensorflow/tensorflow-original.svg
      - name: PyTorch
        web_url: https://github.com/topics/pytorch
        image_url: https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/pytorch/pytorch-original.svg
      - name: Keras
        web_url: https://github.com/topics/keras
        image_url: https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/keras/keras-original.svg
      - name: Kaggle
        web_url: https://github.com/topics/kaggle
        image_url: https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/kaggle/kaggle-original.svg
      - name: Hugging Face
        web_url: https://github.com/topics/huggingface
        image_url: https://huggingface.co/front/assets/huggingface_logo.svg

  - category: Data
    items:
      - name: MySQL
        web_url: https://github.com/topics/mysql
        image_url: https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/mysql/mysql-original-wordmark.svg
      - name: SQLite
        web_url: https://github.com/topics/sqlite
        image_url: https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/sqlite/sqlite-original.svg
      - name: PostgreSQL
        web_url: https://github.com/topics/postgresql
        image_url: https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/postgresql/postgresql-original.svg
      - name: XML
        web_url: https://github.com/topics/xml
        image_url: https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/xml/xml-original.svg
      - name: JSON
        web_url: https://github.com/topics/json
        image_url: https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/json/json-original.svg
      - name: YAML
        web_url: https://github.com/topics/yaml
        image_url: https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/yaml/yaml-original.svg

  - category: Editors & Source Control
    items:
      - name: VS Code
        web_url: https://github.com/topics/vscode
        image_url: https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/vscode/vscode-original.svg
      - name: LaTeX
        web_url: https://github.com/topics/latex
        image_url: https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/latex/latex-original.svg
      - name: Jupyter
        web_url: https://github.com/topics/jupyter
        image_url: https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/jupyter/jupyter-original.svg
      - name: Git
        web_url: https://github.com/topics/git
        image_url: https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/git/git-original.svg
      - name: GitHub
        web_url: https://github.com/topics/github
        image_url: https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/github/github-original.svg
      - name: GitHub Actions
        web_url: https://github.com/topics/github-actions
        image_url: https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/githubactions/githubactions-original.svg

  - category: Other Tools
    items:
      - name: Matplotlib
        web_url: https://github.com/topics/matplotlib
        image_url: https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/matplotlib/matplotlib-original.svg
      - name: Numpy
        web_url: https://github.com/topics/numpy
        image_url: https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/numpy/numpy-original.svg
      - name: Pandas
        web_url: https://github.com/topics/pandas
        image_url: https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/pandas/pandas-original.svg
      - name: Docker
        web_url: https://github.com/topics/docker
        image_url: https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/docker/docker-original.svg
      - name: PyPI
        web_url: https://github.com/topics/pypi
        image_url: https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/pypi/pypi-original.svg
      - name: PNPM
        web_url: https://github.com/topics/pnpm
        image_url: https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/pnpm/pnpm-original.svg
