layout: stacked
style: dark

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: stars
  # sort_by options:
  #   - pushed
  #   - stars
  # limit: 9
  exclude:
    archived: true
    forks: true
    projects:
    # - repo-name

social_media:
  website: https://julenetxaniz.eus
  linkedin: juletxara
  twitter: juletxara
  instagram: juletxara
  facebook: juletxara
  stackoverflow: 12519473
  hackerrank: juletxara
  # behance: your_username
  # dribbble: your_username
  # keybase: your_username
  # mastodon: your_username
  # medium: your_username
  # telegram: your_username
  # unsplash: your_username
  # vk: your_username
  # youtube: your_username

topics:
  - name: Java
    web_url: https://github.com/topics/java
    image_url: https://cdn.jsdelivr.net/gh/devicons/devicon@v2.8.2/icons/java/java-original-wordmark.svg

  - name: JavaScript
    web_url: https://github.com/topics/javascript
    image_url: https://cdn.jsdelivr.net/gh/devicons/devicon@v2.8.2/icons/javascript/javascript-original.svg

  - name: PHP
    web_url: https://github.com/topics/php
    image_url: https://cdn.jsdelivr.net/gh/devicons/devicon@v2.8.2/icons/php/php-original.svg

  - name: Python
    web_url: https://github.com/topics/python
    image_url: https://cdn.jsdelivr.net/gh/devicons/devicon@v2.8.2/icons/python/python-original.svg

  - name: SQL
    web_url: https://github.com/topics/sql
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/sql/sql.png

  - name: HTML
    web_url: https://github.com/topics/html
    image_url: https://cdn.jsdelivr.net/gh/devicons/devicon@v2.8.2/icons/html5/html5-original-wordmark.svg

  - name: CSS
    web_url: https://github.com/topics/css
    image_url: https://cdn.jsdelivr.net/gh/devicons/devicon@v2.8.2/icons/css3/css3-original-wordmark.svg

  - name: Bootstrap
    web_url: https://github.com/topics/bootstrap
    image_url: https://cdn.jsdelivr.net/gh/devicons/devicon@v2.8.2/icons/bootstrap/bootstrap-plain.svg

  - name: Xamarin
    web_url: https://github.com/topics/xamarin
    image_url: https://raw.githubusercontent.com/detain/svg-logos/780f25886640cef088af994181646db2f6b1a3f8/svg/xamarin.svg

  - name: MySQL
    web_url: https://github.com/topics/mysql
    image_url: https://cdn.jsdelivr.net/gh/devicons/devicon@v2.8.2/icons/mysql/mysql-original-wordmark.svg

  - name: Oracle
    web_url: https://github.com/topics/oracle
    image_url: https://cdn.jsdelivr.net/gh/devicons/devicon@v2.8.2/icons/oracle/oracle-original.svg

  - name: Django
    web_url: https://github.com/topics/django
    image_url: https://cdn.jsdelivr.net/gh/devicons/devicon@v2.8.2/icons/django/django-original.svg

  - name: .NET
    web_url: https://github.com/topics/donet
    image_url: https://cdn.jsdelivr.net/gh/devicons/devicon@v2.8.2/icons/dot-net/dot-net-original-wordmark.svg

  - name: Hugo
    web_url: https://github.com/topics/hugo
    image_url: https://cdn.jsdelivr.net/npm/simple-icons@3.0.1/icons/hugo.svg

  - name: Jekyll
    web_url: https://github.com/topics/jekyll
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/jekyll/jekyll.png

  - name: Git
    web_url: https://github.com/topics/git
    image_url: https://www.vectorlogo.zone/logos/git-scm/git-scm-icon.svg

  - name: GitHub
    web_url: https://github.com/topics/github
    image_url: https://raw.githubusercontent.com/github/explore/78df643247d429f6cc873026c0622819ad797942/topics/github/github.png
